version: '3.8'

services:
  barcode_generator:
    container_name: barcode_generator
    build: ./barcode_generator
    ports:
      - 8000:80

  inventory:
    container_name: inventory
    build: ./inventory
    ports:
      - 8001:80

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432