name: CI Barcode Generator

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/ci-reusable.yaml
    with:
      image_name: barcode_generator
      context: ./barcode_generator