name: CI Build Inventory

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/ci-reusable.yaml
    with:
      image_name: inventory
      context: ./inventory